In [2]:
# import it 
import numpy as np

In [26]:
### Arrays on Numpy library

# crate a 1D arr
arr1 = np.array([1,2,3])   
print(arr1)

# crate a 2D arr
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)
a = np.ndim(arr1)
b = np.ndim(arr2)
print(a, b)

# creatign a array of zeroes 
arr3 = np.zeros((2,4)) # 2 rows and 4 columns
print(arr3)

# all one 
arr4 = np.ones((3,3))
print(arr4)

arr5 = np.identity(4)    # made a diagonal matrix with all 1s
print(arr5)

# get continuous array 
arr6 = np.arange(10)   #generate a list in given range - default 0 
print(arr6)
arr7 = np.arange(2,15)  #initial and final values 
print(arr7)
arr8 = np.arange(4,17, 3)  #with the gaps
print(arr8)

# one more with lower, upper range and equidistance with adj element 
arr9 = np.linspace(10, 20, 10)
print(arr9)

arr10 = arr6.copy()
print(arr10)

[1 2 3]
[[1 2 3]
 [4 5 6]]
1 2
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[0 1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 4  7 10 13 16]
[10.         11.11111111 12.22222222 13.33333333 14.44444444 15.55555556
 16.66666667 17.77777778 18.88888889 20.        ]
[0 1 2 3 4 5 6 7 8 9]


In [51]:
### arritbutes and shapes 

arr2.shape   # rows and cols
arr = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
arr.shape

arr.ndim      # ---> 3 
arr2.ndim    # ---> 2

arr.size       # (no.s of items) 8 
b = arr.itemsize  # datatype size like int - 4 , float - 8
print(b)

# dtype
arr.dtype    # --> dtype('int64')

# convert datatype
arr12 = arr.astype('float')
print(arr12)

# 

8
[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]


In [57]:
### python list vs numpy array 
# 1. numpy array store less space then a list 
lista = range(100)
arr13 = np.arange(100)

import sys
print(sys.getsizeof(87) * len(lista))

print(arr13.itemsize * arr13.size)

# 2. speed of numpy array is more then list 
import time 
x = range(100000)
y = range(100000, 200000)

start_time = time.time()
c = [x+y for x,y in zip(x,y)]
end_time = time.time()
print(end_time - start_time)

# now np array
a = np.arange(100000)
b = np.arange(100000, 200000)
start_t = time.time()
d = a+b
end_t =  time.time()
print(end_t - start_t)

2800
800
0.0210723876953125
0.00041294097900390625


In [87]:
### indexing, slicing and iteration
arr15 = np.arange(24)
print("1st", arr15)

arr16 = arr15.reshape(6, 4)
print("2nd\n", arr16)

i = arr1[2]
j = arr1[-1]
print("value at index 2 is:", i, "\nlast index value:", j)

arr16[1]  # --> array([4, 5, 6, 7])
arr16[1:3] #array([[ 4,  5,  6,  7],
            #      [ 8,  9, 10, 11]])

arr16[0:7:3]    # similar to that equidistance in arange
arr16[:, 2]     # : means all rows and ,2 tell which col u need 
                # -->  array([ 2,  6, 10, 14, 18, 22])
arr16[:, 1:3]   # --> array([[ 1,  2],
                    #       [ 5,  6],
                    #       [ 9, 10],
                    #       [13, 14],
                    #       [17, 18],
                    #       [21, 22]])

arr16[3, 1:3]       # --> array([13, 14])
arr16[4:6, 2:4]     # --> array([[18, 19],
                    #           [22, 23]])


## iteration 
print("No Iteration:")
for i in arr16:
    print(i)

print("Iteration:")
for i in np.nditer(arr16):
    print(i) 


1st [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
2nd
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
value at index 2 is: 3 
last index value: 3
No Iteration:
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]
Iteration:
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [92]:
### Numpy Operations
arr_x = np.array([1, 2, 3])
arr_y = np.array([4, 5, 6])


In [125]:
arr_x + arr_y          # --> element wise Additon  
arr_x * arr_y          # --> element wise Mutltiplication 
arr_x - arr_y          

arr_x * 6              # --> array([ 6, 12, 18])
arr_x > 1              # --> array([False,  True,  True])
arr3 = np.arange(6).reshape(2,3)  # --> array([[0, 1, 2],
                                  #          [3, 4, 5]])
arr4 = np.arange(6, 12).reshape(3, 2) # --> array([[ 6,  7],
                                      #         [ 8,  9],
                                      #         [10, 11]]) 
# order should be the same 
arr3.dot(arr4)         #  --> array([[ 28,  31],
                       #            [100, 112]])

arr3.max()

arr4.min()  
arr3.min(axis = 0)      # every col min element  --> rray([0, 1, 2])
arr3.min(axis = 1)      # every row min element  --> array([0, 3])

arr3.sum()              # --> np.int64(15)
arr3.sum(axis = 0)      # --> array([3, 5, 7])

arr3.mean()               # --> np.float64(2.5)
arr3.mean(axis=0)         # --> array([1.5, 2.5, 3.5])

arr3.std()              # --> np.float64(1.707825127659933)


np.sin(arr3)
np.median(arr3)
np.exp(arr_x)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [139]:
### Reshapign Numpy Arrays

# 1. Ravel - do convert nd-array to 1D array 
arr4.ravel()
 
# 2. Reshape - seen 

# 3. Transpose
A = arr4.transpose()
A
# 4. Stacking
arr1 = np.arange(12,18).reshape(2,3)
arr1
np.hstack((arr1, arr3))    # in hstack(tup, dtype, casting) 
                        # -->    array([[12, 13, 14,  0,  1,  2],
                        #              [15, 16, 17,  3,  4,  5]])

np.vstack((arr3, arr1))         # -->   array([[ 0,  1,  2],
                                #              [ 3,  4,  5],
                                #              [12, 13, 14],
                                #              [15, 16, 17]])

# 5. Splitting
np.hsplit(arr3, 3)        # --> [array([[0], [3]]),
                          #      array([[1], [4]]),
                          #      array([[2], [5]])]

np.vsplit(arr3, 2)        # --> [array([[0, 1, 2]]), array([[3, 4, 5]])]

[array([[0, 1, 2]]), array([[3, 4, 5]])]

In [141]:
### FANCY INDEXING 

# used when require a index that is not continuous 
arr8 = np.arange(24).reshape(6, 4)
arr8
arr8[[0,2,5]]  # this is fancy indexing 


array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [20, 21, 22, 23]])

In [149]:
### INDEXING USING BOOLEAN ARRAYS

B = np.random.randint(low=1, high=100, size=20).reshape(4, 5)
B
B > 60
B[(B>60) & (B%2 != 0)]     # greater thna 60 and are odd 

array([85, 67, 89, 91], dtype=int32)

In [ ]:
### GRAPHS USING NUMPY

In [151]:
### BROADCASTING 
# - RULES FOR BROADCASTING 

In [152]:
### RANDOM LIBRARY
np.random.random()

0.9437999131500148

In [159]:
np.random.seed(25)
np.random.random()

0.8701241366272119

In [160]:
np.random.uniform(3, 10) # low and high and size

7.0759385007079185

In [179]:
a = np.random.uniform(5,80, 20).reshape(5,4)

print(a)
print("Shape:", a.shape)
print("np.argmin(a):", np.argmin(a))
print("np.argmax(a):", np.argmax(a))
c = a[a%2 == 1] = -1
print(c)

[[39.00501007 38.55764178 54.51610872 17.03573173]
 [65.55706854 40.65906351 27.75308632 27.84513393]
 [47.13779316 76.44537032 45.713508   60.23706848]
 [60.69787105 78.20899645 32.69269047 75.1615426 ]
 [48.96770705 74.49240461 73.76663114 23.20890773]]
Shape: (5, 4)
np.argmin(a): 3
np.argmax(a): 13
[]
